### ISSUE TITLE
Make use of `useClipboard` instead of `navigator.clipboard`

### ISSUE THREAD

**Issue by allejo** [allejo/json-reshaper#9]
Instead of using `navigator.clipboard`, which is async, make use of [`useCopyToClipboard`](https://usehooks-ts.com/react-hook/use-copy-to-clipboard) from the `usehooks-ts` project, that's already included in this project.

https://github.com/allejo/json-reshaper/blob/cf38de784445909b35de862ca250ea4e72b9f5ca/src/components/OutputPreview.tsx#L42-L49

**Comment by F-BEDDIAF** [comment]
hello @allejo ,
can I take this task?
also as I noticed, when clicking on the copy button, nothing is said or shown that the transFormedText is copied !!?
can I add a toaster to do that alert? or you can suggest any package you see it can handle this issue.

**Comment by F-BEDDIAF** [comment]
![Screenshot 2023-08-19 135637](https://github.com/allejo/json-reshaper/assets/62912697/1ed733ba-cea3-4ab4-8ba8-32a08918f3d6)

**Comment by allejo** [comment]
The popover/notification issue is defined in #10. But I'm totally okay with your PR and your suggestion for using `react-hot-toast` 😄
